#!/bin/bash
#$ -N analysis
#$ -cwd
#$ -l rl9=true
#$ -pe sharedmem 4
#$ -l h_vmem=60G  # Memory limit (modify as needed)
#$ -j y
#$ -m ea
#$ -M s2749646@ed.ac.uk

# Initialise the environment modules
. /etc/profile.d/modules.sh

module load roslin/bwa/0.7.18

# Run bwa
bwa index GCA_905237065.1
